### ISSUE TITLE
Unable to Create Site Pair with HCX 4.1 in VMC

### ISSUE THREAD

**Issue by uprightvinyl** [adeleporte/terraform-provider-hcx#7]
### Expected Behaviour:

With HCX 4.1.0.18180940, running on a VMC SDDC 1.14v4, I can pair HCX running in two SDDCs. This has worked in the past.

### Current Behaviour

Using provider version 4.1.0, 4.0 and 3.4.0, an error is thrown and the pairing is not successful. The following output is using 4.1.0:

```
hcx_site_pairing.sddc_a_to_b: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with hcx_site_pairing.sddc_a_to_b,
│   on main.tf line 594, in resource "hcx_site_pairing" "sddc_a_to_b":
│  594: resource "hcx_site_pairing" "sddc_a_to_b" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-hcx_v0.4.1 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 44 [running]:
main.resourceSitePairingCreate(0x19bf960, 0xc000296ea0, 0xc00019f900, 0x17dddc0, 0xc0001e42a0, 0xc0002ee930, 0x1460bda, 0xc00000d740)
        github.com/adeleporte/terraform-provider-hcx/resource_site_pairing.go:100 +0xefb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000145ce0, 0x19bf8e0, 0xc00009ac40, 0xc00019f900, 0x17dddc0, 0xc0001e42a0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.2.0/helper/schema/resource.go:275 +0x1ec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000145ce0, 0x19bf8e0, 0xc00009ac40, 0xc00029d570, 0xc00000d740, 0x17dddc0, 0xc0001e42a0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.2.0/helper/schema/resource.go:386 +0x681
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00026a4a0, 0x19bf8e0, 0xc00009ac40, 0xc0002c67d0, 0xc00009ac40, 0xc000296800, 0x19ccb40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.2.0/helper/schema/grpc_provider.go:951 +0x8b2
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00000ce60, 0x19bf8e0, 0xc00009ac40, 0xc00029d340, 0xc00000ce60, 0xc0002ce000, 0xc000621ba0)
        github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/server/server.go:331 +0xac
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x18590c0, 0xc00000ce60, 0x19bf9a0, 0xc0002ce000, 0xc0002968a0, 0x0, 0x19bf9a0, 0xc0002ce000, 0xc000220f00, 0x248)
        github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002b2e00, 0x19c96e0, 0xc000082780, 0xc0001e6700, 0xc0002fea80, 0x1ef1c40, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x50a
google.golang.org/grpc.(*Server).handleStream(0xc0002b2e00, 0x19c96e0, 0xc000082780, 0xc0001e6700, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xcfd
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00034a200, 0xc0002b2e00, 0x19c96e0, 0xc000082780, 0xc0001e6700)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x204

Error: The terraform-provider-hcx_v0.4.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Possible Solution

No ideas at present. Has the `hcx_site_pairing` resource been tested with HCX 4.x?

### Steps to recreate

```
provider "hcx" {
  alias = "sddc_a"
  hcx      = "https://hcx.sddc-1-2-3-4.vmwarevmc.com/"
  username = "cloudadmin@vmc.local"
  password = "password"
}

provider "hcx" {
  alias = "sddc_b"
  hcx      = "https://hcx.sddc-5-6-7-8.vmwarevmc.com/"
  username = "cloudadmin@vmc.local"
  password = "password"
}

resource "hcx_site_pairing" "sddc_a_to_b" {
  provider = hcx.sddc_a
  url      = "https://hcx.sddc-5-6-7-8.vmwarevmc.com/"
  username = "cloudadmin@vmc.local"
  password = "password"
}

resource "hcx_site_pairing" "sddc_b_to_a" {
  provider = hcx.sddc_b
  url      = "https://hcx.sddc-1-2-3-4.vmwarevmc.com/"
  username = "cloudadmin@vmc.local"
  password = "password"

  depends_on = [hcx_site_pairing.sddc_a_to_b]
}
```

### Context (Environment)

```
terraform version
Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/adeleporte/hcx v0.4.1
```

**Comment by adeleporte** [comment]
Hi,
looks like some API calls took very long time to answer.
The timeout was set to 30s, so I've increased it to 60s, and changed the TF error message to be more verbose.
v0.4.2 includes these changes, please let me know if this fixes the issue.

https://registry.terraform.io/providers/adeleporte/hcx/latest

**Comment by adeleporte** [comment]
v0.4.2 fixes this issue
